#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for documentation.

###########################################################################################
# ACTION KEYS
###########################################################################################
###### WM Specific Keys ######
riverctl map normal Super Q close                 # Close the focused view
riverctl map normal Super+Shift A toggle-float    # Toggle float
riverctl map normal Super F toggle-fullscreen     # Toggle fullscreen
#riverctl map normal Super Return zoom            # Bump the focused view to the top of the layout stack

###### Quick Session Managing ######
riverctl map normal Super+Control+Shift Q exit    # Exit wayland session/compositor

###### EWW Keys ######
###### Wofi Menu Keys ######

###### App Keys ######
riverctl map normal Super Return spawn 'kitty -1'
riverctl map normal Super+Shift Return spawn 'footclient --app-id "foot-float"'
riverctl map normal Super W spawn 'waterfox-g'


###########################################################################################
# AUTOSTART                                                                               #
###########################################################################################
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "/usr/lib/polkit-kde-authentification-agent-1"
riverctl spawn "foot --server"
#riverctl spawn "emacs --daemon"
#riverctl spawn "mako"
riverctl spawn "dunst"
riverctl spawn "udiskie"
riverctl spawn "swaybg -i ~/.config/hypr/wallpapers/default-wallpaper"
riverctl spawn "udev-block-notify"
#riverctl spawn "waybar"
#riverctl spawn "nm-applet --indicator"

# Clipboard manager
riverctl spawn "wl-clip-persist --clipboard regular"         # Persistent clipboard
riverctl spawn "wl-paste --watch cliphist store"             # Store in clipboard history (cliphist wipe to clear the database)

# Scripts
riverctl spawn "~/.config/hypr/scripts/gtkthemes"          # Apply themes
#riverctl spawn "~/.config/hypr/scripts/idle-handler"       # Screen locking when idle


###########################################################################################
# SUPER + SHIFT + ... KEYS                                                                #
###########################################################################################
####### Screenshot ######
riverctl map normal Super Print spawn "grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | wl-copy"

# Change Wallpaper
riverctl map normal Super+Shift N spawn "~/.config/hypr/scripts/wallpaper"

###########################################################################################
# FUNCTION KEYS                                                                           #
###########################################################################################
# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map-repeat $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map-repeat $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map-repeat $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map-repeat $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map-repeat $mode None XF86MonBrightnessDown spawn 'light -U 5'

    # Experimental - Suspend on closed laptop lid
    #riverctl map-switch $mode close "systemctl suspend"
done


###########################################################################################
# WINDOW MANAGER OPERATION KEYS                                                           #
###########################################################################################
####### Move floating windows #######
#riverctl map normal Super+Alt H move left 100
#riverctl map normal Super+Alt J move down 100
#riverctl map normal Super+Alt K move up 100
#riverctl map normal Super+Alt L move right 100

####### Snap floating windows to screen edges #######
#riverctl map normal Super+Alt+Control H snap left
#riverctl map normal Super+Alt+Control J snap down
#riverctl map normal Super+Alt+Control K snap up
#riverctl map normal Super+Alt+Control L snap right

####### Resize floating windows #######
#riverctl map normal Super+Alt+Shift H resize horizontal -100
#riverctl map normal Super+Alt+Shift J resize vertical 100
#riverctl map normal Super+Alt+Shift K resize vertical -100
#riverctl map normal Super+Alt+Shift L resize horizontal 100

####### Move Focus #######
# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

####### Move Window #######
# Swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
# Mouse move and resize (floating)
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

####### Move Window to Output #######
# Send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous
####### Move Focus to Output #######
# Focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

###########################################################################################
# RIVERTILE                                                                               #
###########################################################################################
# Change layout orientation
#riverctl map normal Super+Shift K send-layout-cmd rivertile "main-location top"
#riverctl map normal Super+Shift H send-layout-cmd rivertile "main-location right"
#riverctl map normal Super+Shift J send-layout-cmd rivertile "main-location bottom"
#riverctl map normal Super+Shift L send-layout-cmd rivertile "main-location left"

####### Resize Window #######
riverctl map normal Super+Alt H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Alt L send-layout-cmd rivertile "main-ratio +0.05"
# Window Split Ratio
# Increment/decrement the main count of rivertile(1)
#riverctl map normal Super+Control H send-layout-cmd rivertile "main-count +1"
#riverctl map normal Super+Control L send-layout-cmd rivertile "main-count -1"


###########################################################################################
# CUSTOM MODE                                                                             #
###########################################################################################
# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
#riverctl declare-mode passthrough

# Enter passthrough mode
#riverctl map normal Super F11 enter-mode passthrough

# Return to normal mode
#riverctl map passthrough Super F11 enter-mode normal


###########################################################################################
# TAG MANAGEMENT                                                                          #
###########################################################################################
# Single Tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done


# All Tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags            # Focus all tags
#riverctl map normal Super+Shift 0 set-view-tags $all_tags        # Tag focused view with all tags


###########################################################################################
# WINDOW RULES                                                                            #
###########################################################################################
# Floating windows
riverctl float-filter-add title "Picture-in-Picture"
riverctl float-filter-add app-id "musikcube"
riverctl float-filter-add app-id "foot-float"

# Set app-ids and titles of windows which should not use client side decorations (Xwayland apps)
#riverctl csd-filter-remove app-id "logseq"


###########################################################################################
# MISCS SETTINGS                                                                          #
###########################################################################################
# Background and Border Colors
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Hide cursor after 5s
riverctl hide-cursor timeout 5000

# Hide cursor when typing
riverctl hide-cursor when-typing enabled

# Cursor theme (optionally add 24 as size)
riverctl xcursor-theme Numix-Cursor-Light 24

# Swap caps with escape
#riverctl keyboard-layout "caps:swapescape"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 3 -outer-padding 3 &
