#!/bin/sh

# See the river(1) and riverctl(1) man pages for documentation.

###########################################################################################
# ACTION KEYS
###########################################################################################
###### WM Specific Keys ######
riverctl map normal Super Q close                 # Close the focused view
riverctl map normal Super+Shift A toggle-float    # Toggle float
riverctl map normal Super F toggle-fullscreen     # Toggle fullscreen
#riverctl map normal Super Return zoom            # Bump the focused view to the top of the layout stack

###### Quick Session Managing ######
riverctl map normal Super+Control+Shift Q exit                                   # Exit wayland session/compositor
riverctl map normal Super+Control+Shift Delete spawn "systemctl poweroff"        # Rescue board option
riverctl map normal Super Y spawn "~/.config/hypr/scripts/lock"                  # Lock screen
riverctl map normal Super+Shift Y spawn "lock && sleep 1 && systemctl suspend"   # Lock and suspend

###### Wofi Menu Keys ######
riverctl map normal Super P spawn "pkill wlogout || wlogout"                     # Session manager
riverctl map normal Super U spawn "pkill wofi || wofi-beats.sh"                  # Rofi radio
riverctl map normal Super C spawn "pkill wofi || wofi-clipboard.sh"              # Clipboard menu
riverctl map normal Super+Shift Semicolon spawn "pkill wofi || wofi-emoji.sh"    # Emoji menu

###### App Keys ######
riverctl map normal Super Return spawn 'kitty -1'
riverctl map normal Super W spawn 'waterfox-g'
#riverctl map normal Super E spawn 'emacsclient -c -a emacs'
riverctl map normal Super N spawn 'footclient -T newsboat -a newsboat -e newsboat'

####### Floating Views #######
riverctl map normal Super+Shift Return spawn 'footclient -a "foot-float"'        # Foot
riverctl map normal Super+Shift Z spawn 'webcam'                                 # Webcam
riverctl map normal Super T spawn 'athena-welcome'                               # Athena welcome
riverctl map normal Super V spawn 'hacking-variables'                            # Payload list
riverctl map normal Super X spawn 'role-viewer'                                  # Tools list 

####### Fun Commands: musikcube, btop, cava, tty-clock, cmatrix, neofetch, pipes, mpv, waifu ######
riverctl map normal Super+Shift Escape spawn 'footclient -a btop -e btop'                                  # Btop
riverctl map normal Super+Control N spawn 'footclient -a musikcube -e musikcube'                           # Music
riverctl map normal Super+Control C spawn 'footclient -a cava -e cava'                                     # Cava
riverctl map normal Super+Control U spawn 'footclient -a clock -e tty-clock -c -C 6 -r -s -f "%A, %B, %d"' # Clock
riverctl map normal Super+Control P spawn 'footclient -a pipes -e ~/.config/zsh/bash-scripts/pipes.sh'     # Pipes
riverctl map normal Super+Control M spawn 'footclient -a cmatrix -e cmatrix -a'                            # Matrix

###### Updates ######
riverctl map normal Super+Control+Shift C spawn 'notify-send -u low -t 4000 "Updating cheatsheets..." && footclient --title update -a update -e ~/.config/hypr/scripts/cheatsheets push'
riverctl map normal Super+Control M spawn 'notify-send -u low -t 4000 -i "$HOME/.config/mako/icons/mirror.png" "Updating mirrors..." && footclient --title reflector -a reflector -e sudo reflector --score 100 --fastest 10 --number 10 --verbose --save /etc/pacman.d/mirrorlist'
riverctl map normal Super+Control M spawn 'notify-send -u low -t 4000 -i "$HOME/.config/mako/icons/keyring.png" "Refreshing keyrings..." && footclient --title keys -a keys -e bash ~/.config/hypr/scripts/fix-keys'
riverctl map normal Super+Control M spawn 'notify-send -u low -t 4000 -i "$HOME/.config/mako/icons/update.png" "Updating system..." && footclient --title yay -a yay -e yay --noconfirm -Syu'

####### Screenshot ######
# for screenshot keybind
$w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
$w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
riverctl map normal None Print spawn 'grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | wl-copy'
riverctl map normal Shift Print spawn 'grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | swappy -f -'
# Screenshot Window
riverctl map normal Super Print spawn 'grim -g "$w_pos $w_size" - | wl-copy'
riverctl map normal Super+Shift Print spawn 'grim -g "$w_pos $w_size" - | swappy -f -'
# Screenshot Full Screen
riverctl map normal Control Print spawn 'grim - | wl-copy'
riverctl map normal Control+Shift Print spawn 'grim - | swappy -f -'

####### Caffeine #######
riverctl map normal Super+Shift C spawn '~/.config/hypr/scripts/caffeine'

####### Swaybg #######
riverctl map normal Super+Alt B spawn "~/.config/hypr/scripts/wallpaper"


###########################################################################################
# AUTOSTART                                                                               #
###########################################################################################
####### Autostart ######
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "/usr/lib/polkit-kde-authentification-agent-1"
riverctl spawn "foot --server"
#riverctl spawn "emacs --daemon"
#riverctl spawn "mako"
riverctl spawn "dunst"
riverctl spawn "udiskie"
riverctl spawn "swaybg -i ~/.config/hypr/wallpapers/default-wallpaper"
riverctl spawn "udev-block-notify"
#riverctl spawn "waybar"
#riverctl spawn "nm-applet --indicator"

####### Clipboard manager ######
riverctl spawn "wl-clip-persist --clipboard regular"         # Persistent clipboard
riverctl spawn "wl-paste --watch cliphist store"             # Store in clipboard history (cliphist wipe to clear the database)

####### Scripts ######
#riverctl spawn "~/.config/hypr/scripts/idle-handler"         # Screen locking when idle

####### GTK Themes ######
riverctl spawn 'gsettings set org.gnome.desktop.interface gtk-theme "cachyos-nord"'
riverctl spawn 'gsettings set org.gnome.desktop.interface icon-theme "Papirus"'
riverctl spawn 'gsettings set org.gnome.desktop.interface cursor-theme "Numix-Cursor-Light"'
riverctl spawn 'gsettings set org.gnome.desktop.interface font-name "Sans 10"'




###########################################################################################
# FUNCTION KEYS                                                                           #
###########################################################################################
# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Suspend on closed laptop lid
#riverctl map-switch normal lid close 'lock && sleep 1 && systemctl suspend'
#riverctl map-switch locked lid close 'systemctl suspend'


###########################################################################################
# WINDOW MANAGER OPERATION KEYS                                                           #
###########################################################################################
####### Move floating views #######
#riverctl map normal Super+Alt H move left 100
#riverctl map normal Super+Alt J move down 100
#riverctl map normal Super+Alt K move up 100
#riverctl map normal Super+Alt L move right 100

####### Snap floating views to screen edges #######
#riverctl map normal Super+Alt+Control H snap left
#riverctl map normal Super+Alt+Control J snap down
#riverctl map normal Super+Alt+Control K snap up
#riverctl map normal Super+Alt+Control L snap right

####### Resize floating views #######
#riverctl map normal Super+Alt+Shift H resize horizontal -100
#riverctl map normal Super+Alt+Shift J resize vertical 100
#riverctl map normal Super+Alt+Shift K resize vertical -100
#riverctl map normal Super+Alt+Shift L resize horizontal 100
# Mouse move and resize (floating)
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

####### Move Focus #######
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

####### Move Views #######
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

####### Move Focus to Output #######
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

####### Move View to Output #######
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous


###########################################################################################
# KILE LAYOUT GENERATOR                                                                   #
###########################################################################################
# Decrease/increase the main ratio of kile
riverctl map normal Super+Alt H send-layout-cmd kile "mod-main-ratio -0.05"
riverctl map normal Super+Alt L send-layout-cmd kile "mod-main-ratio +0.05"

# Increment/decrement the main count of kile - what is this even
#riverctl map normal Super+Control H send-layout-cmd kile "mod-main-count +1"
#riverctl map normal Super+Control L send-layout-cmd kile "mod-main-count -1"


###########################################################################################
# CUSTOM MODE                                                                             #
###########################################################################################
# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
#riverctl declare-mode passthrough

# Enter passthrough mode
#riverctl map normal Super F11 enter-mode passthrough

# Return to normal mode
#riverctl map passthrough Super F11 enter-mode normal


###########################################################################################
# TAG MANAGEMENT                                                                          #
###########################################################################################
####### Single Tags #######
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done


# All Tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags            # Focus all tags
#riverctl map normal Super+Shift 0 set-view-tags $all_tags        # Tag focused view with all tags


###########################################################################################
# VIEW RULES                                                                            #
###########################################################################################
####### Floating Views #######
riverctl float-filter-add title "Picture-in-Picture"
riverctl float-filter-add app-id "musikcube"
riverctl float-filter-add app-id "foot-float"
riverctl float-filter-add app-id "swappy"

# Set app-ids and titles of views which should not use client side decorations (Xwayland apps)
#riverctl csd-filter-remove app-id "logseq"


###########################################################################################
# MISCS SETTINGS                                                                          #
###########################################################################################
####### Outputs #######
#wlr-randr --output
#outputs['eDP-1']="{mode='1920x1080', pos='0,0', transform='normal', scale='1.000000', preferred=true}"
#outputs['DP-2']="{mode='2560x1080', pos='1920,0', transform='normal', scale='1.000000', preferred=true}"

####### Inputs #######
# Mouse
riverctl input pointer-5426-92-Razer_Razer_DeathAdder_Elite pointer-accel 0
riverctl input pointer-5426-92-Razer_Razer_DeathAdder_Elite accel-profile flat
# Touchpad
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad accel-profile flat
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad pointer-accel 1.0
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad events disabled-on-external-mouse
#riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad click-method clickfinger
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad drag enabled
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad disable-while-typing enabled
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad middle-emulation disabled
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad natural-scroll enabled
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad tap enabled
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad tap-button-map left-right-middle
riverctl input pointer-1267-12738-ELAN0752:00_04F3:31C2_Touchpad scroll-method two-finger

####### River Options #######
riverctl attach-mode top
riverctl background-color 0x002b36
riverctl border-color-focused 0x7AA2F7FF
riverctl border-color-unfocused 0x04404aaa
#riverctl border-color-urgent
riverctl border-width 2
riverctl default-layout kile
# Keyboard
riverctl keyboard-layout us
#riverctl keyboard-options caps:swapescape
riverctl set-repeat 50 300
# Cursor
riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled
riverctl xcursor-theme Numix-Cursor-Light 24
riverctl set-cursor-warp disabled
riverctl focus-follows-cursor on-output-change

# Start the default layout generator
kile &
