#!/bin/bash

if [ -f "/tmp/toggle-gamemode" ]; then
    rm "/tmp/toggle-gamemode"
    notify-send -t 3000 "Gamemode Disabled"
    riverctl unmap normal Shift D
    riverctl unmap normal Shift W
    riverctl unmap normal Shift E
else
    touch "/tmp/toggle-gamemode"
    notify-send -t 3000 "Gamemode Enabled"
    riverctl map normal Shift D spawn '~/.config/river/scripts/s-d.sh'
    riverctl map normal Shift W spawn '~/.config/river/scripts/s-w.sh'
    riverctl map normal Shift E spawn '~/.config/river/scripts/s-e.sh'
fi
