#!/bin/bash

# End all of the auto-spawns processes
killall polkit-kde-authentication-agent-1
killall dunst
killall gammastep
killall idle-handler
killall cmst
killall udiskie
killall waybar
killall foot
killall electron
killall udev-block-notify
killall wl-clip-persist
killall wl-paste
killall wallpaper-changer
killall emacs
killall battery-notif
killall superproductivity
killall swaybg
killall kitty
killall rivertile

# Reload river
~/.config/river/init
