#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "M" "N" "U" "P")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if 'waterfox-g' process is running
is_waterfox_running() {
    pgrep -x "waterfox-g" >/dev/null
}

is_profile_running() {
    pgrep -a "waterfox-g" | grep -i "work" >/dev/null
}

# Focus on tag "W" if 'waterfox-g' is not running, else just focus
if ! is_waterfox_running; then
    focus_tag 3
    # Spawn 'waterfox-g' only if it was not running
    riverctl spawn 'waterfox-g -P work --new-window'
else
    # Check if it's running with profile, if so, focus on tag "W"
    if is_profile_running; then
        focus_tag 3
    else
        focus_tag 3
        riverctl spawn 'waterfox-g -P work --new-window'
    fi
fi
