#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "U" "N" "P" "H" "L")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if 'firefox' process is running
is_firefox_running() {
    pgrep -a "firefox" | grep "default" >/dev/null
}

# Focus on tag "W" if 'firefox' is not running, else just focus
if ! is_firefox_running; then
    focus_tag 3
    # Spawn 'firefox' only if it was not running
    riverctl spawn 'firefox -P default --new-window'
else
    focus_tag 3
fi
