#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "M" "N" "P" "U")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if 'electron' process is running
is_electron_running() {
    pgrep -x "electron" >/dev/null
}

# Focus on tag "W" if 'webcord' is not running, else just focus
if ! is_electron_running; then
    focus_tag 5
    # Spawn 'webcord' only if it was not running
    riverctl spawn 'webcord'
else
    focus_tag 5
    # Spawn 'webcord' command to open up client, the daemon is ran from autostart
    riverctl spawn 'webcord'
fi
