#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "U" "N" "P" "H" "L")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if 'kitty-emacs-code' process is running
is_kitty_running() {
    lswt | grep kitty-code >/dev/null
}

# Focus on tag "H" if 'kitty-emacs-code' is not running, else just focus
if ! is_kitty_running; then
    focus_tag 5  # Use tag "H" (tag number 5)
    # Spawn kitty only if it was not running
    riverctl spawn 'kitty -1 -T kitty-code --class kitty-code --session ~/.config/kitty/session-emacs-code'
else
    focus_tag 5  # Use tag "H" (tag number 5)
fi
