#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "H" "N" "U" "P")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if the emacs process is running with specific command
is_emacs_running_with_command() {
    pgrep -af "emacsclient -c --eval" >/dev/null
}

# Focus on tag "P" and spawn Emacs with the desired command if it's not running
focus_tag 8  # Use tag "P" (tag number 8)

if ! is_emacs_running_with_command; then
    # Spawn Emacs only if it was not running with the specific command
    riverctl spawn 'emacsclient -c --eval "(open-org-agenda-frame)"'
fi
