#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "M" "N" "P" "U")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if 'waterfox-g' process is running
is_waterfox_running() {
    pgrep -a "waterfox-g" | grep "default-release" >/dev/null
}

# Focus on tag "W" if 'waterfox-g' is not running, else just focus
if ! is_waterfox_running; then
    focus_tag 3
    # Spawn 'waterfox-g' only if it was not running
    riverctl spawn 'waterfox-g -P default-release'
else
    focus_tag 3
fi
