#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "M" "N" "P" "U")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if 'logseq-desktop' process is running
is_logseq_running() {
    pgrep -x "logseq" >/dev/null
}

# Focus on tag "E" if 'logseq-desktop' is not running, else just focus
if ! is_logseq_running; then
    focus_tag 4  # Use tag "E" (tag number 4)
    # Spawn 'logseq-desktop' only if it was not running
    riverctl spawn 'logseq'
else
    focus_tag 4  # Use tag "E" (tag number 4)
fi
