#!/bin/bash

# Define the letter tags
tags=("I" "O" "W" "E" "U" "N" "P" "H" "L")

# Function to focus a specific tag
focus_tag() {
    tag=$1
    tags_bit=$((1 << (tag - 1)))
    riverctl set-focused-tags "$tags_bit"
}

# Function to check if the emacs process is running with specific command
is_emacs_running_with_command() {
    lswt | grep kitty-agenda >/dev/null
    #pgrep -af "emacsclient -nw --eval" >/dev/null
}

# Focus on tag "P" and spawn Emacs with the desired command if it's not running
focus_tag 7  # Use tag "P" (tag number 7)

if ! is_emacs_running_with_command; then
    # Spawn Emacs only if it was not running with the specific command
    riverctl spawn 'kitty -1 -T kitty-agenda --class kitty-agenda --session ~/.config/kitty/session-agenda'
fi
